### ISSUE TITLE
Manifest spec within-scope algo better

### ISSUE THREAD

**Issue by kenchris** [w3c/nfc#35]
The within scope algorithm from the manifest spec doesn't talk about substrings but about starting with the url. Here it is in its entirety: 

A navigation scope is a [URL] that represents the set of URLs to which an application context can be navigated while the manifest is applied. To determine if a URL is within the navigation scope, the user agent must run the within scope algorithm.

A string targetURL is said the be within scope of navigation scope scopeURL if the following algorithm returns true:

If scopeURL is undefined (i.e., it is unbounded because of an error or it was not declared in the manifest), return true.
Let target be a new URL using targetURL as input. If target is failure, return false.
If target is same origin as scope and target's pathname starts with scope's pathname, return true.
Otherwise, return false.

**Comment by kenchris** [comment]
Maybe use this:

If registeredScope is undefined (not defined in regOptions), then let scope be the calling web app's document base URL. Otherwise let scope be registeredScope.

If url is same origin as scope and url's pathname starts with scope's pathname, return true.
Otherwise, return false.

**Comment by zolkis** [comment]
Fine with me.
