### ISSUE TITLE
delete master branch and just use gh-pages

### ISSUE THREAD

**Issue by kenchris** [w3c/nfc#44]
Marcos also says that is the way to go! Let's do it

**Comment by zolkis** [comment]
+1

**Comment by zolkis** [comment]
github repo owner can do it, I cannot. I deleted my own fork's master, but that's it.

**Comment by marcoscaceres** [comment]
@darobin, can you help quickly? Just need you to switch this to gh-pages as main branch?

**Comment by darobin** [comment]
It's a done thing sweetheart.

**Comment by kenchris** [comment]
Thanks! lets close this one then!
