### ISSUE TITLE
Will there be a way to read the NFCTag's UID?

### ISSUE THREAD

**Issue by kontza** [w3c/nfc#91]
I browsed through the specification, and didn't find a mention on how an application could read/acquire the NFC tag's UID. Why is that? My company has deployed tens of thousands of NFC tags to our customers, and for us the most important thing about NFC tags is the UID.

**Comment by zolkis** [comment]
Do you mean the NDEF ID field? If yes, then - by the current thinking - it's used by the Web NFC implementations, contains the writing scope, and it is visible to webpages. In other words, it's a special use of the ID. The main use case with this API is that web pages should see mainly tags designed for the web browser usage. Reading 'legacy' tags is possible, but subject to security policies. 

However, technically it would be possible to expose the ID field for apps use, if you have a strong use case for it and can solve the security implications.

**Comment by zolkis** [comment]
BTW, did you mean to ask on https://github.com/w3c/web-nfc/issues? This working group is closed, and the spec is developed in the https://www.w3.org/community/web-nfc/.
I can migrate this issue there.

**Comment by zolkis** [comment]
This issue was moved to w3c/web-nfc#24
